#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=0,1 python -u train.py \
	--gpu_ids 0,1 \
	--display_freq 100 \
	--seed 123 \
	--name trgv2 \
	--csv_path_train dataset/ARKitFace/ARKitFace_list/list/ARKitFace_train.csv \
	--csv_path_test dataset/ARKitFace/ARKitFace_list/list/ARKitFace_test.csv \
	--num_threads 16 \
	--batch_size 256 \
	--n_epochs 20 \
	--n_epochs_decay 10 \
	--dataset_mode arkit \
	--img_size 192 \
	--lr 1e-4 \
	--train_sampling 1\
  --loop_loss_weight 0.5 \
  --vertex_world_weight 20.0 \
	--vertex_cam_weight 2.0 \
	--lmk68_loss_weight 1.25 \
	--rotmat_loss_weight 10.0 \
	--debugging
